# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rolesetup', '0001_initial'),
        ('project', '0004_ionicnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('key_id', models.CharField(max_length=100)),
                ('old_key', models.CharField(max_length=100)),
                ('pid', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='EditedUsersList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_id', models.CharField(max_length=100)),
                ('user_old_email', models.CharField(max_length=100)),
                ('pid', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('db_status', models.CharField(choices=[('new', 'new'), ('edited', 'edited'), ('updated', 'updated'), ('deleted', 'deleted')], max_length=250)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=100, null=True)),
                ('login_type', models.CharField(choices=[('otp', 'OTP'), ('form', 'Form'), ('bar', 'Barcode')], max_length=20, null=True)),
                ('bgcolor', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('red', 'Red')], max_length=250)),
                ('regeisterion_page', models.BooleanField(default=False)),
                ('logoimg', models.FileField(blank=True, null=True, upload_to='static/ionicsrc/images/logo')),
                ('createpage', models.BooleanField(default=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('db_status', models.CharField(choices=[('new', 'new'), ('edited', 'edited'), ('updated', 'updated'), ('deleted', 'deleted')], max_length=250)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rolesetup.Role')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userlist',
            unique_together=set([('project_id', 'email_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='generalinfo',
            unique_together=set([('project_id', 'key')]),
        ),
    ]
