# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logintemplate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rolesetup.Role'),
            preserve_default=False,
        ),
    ]
