# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncmaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='synccolumndetails',
            name='db_status',
            field=models.CharField(choices=[('new', 'new'), ('edited', 'edited'), ('updated', 'updated'), ('deleted', 'deleted')], default='new', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='synctabledetails',
            name='db_status',
            field=models.CharField(choices=[('new', 'new'), ('edited', 'edited'), ('updated', 'updated'), ('deleted', 'deleted')], default='new', max_length=250),
            preserve_default=False,
        ),
    ]
