# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syncmaster', '0004_auto_20180205_1431'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EditedUsersList',
            new_name='EditedTableMap',
        ),
    ]
