# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180110_1527'),
        ('syncmaster', '0005_auto_20180205_1501'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='synctabledetails',
            unique_together=set([('sourcetable', 'targettable', 'projectid')]),
        ),
    ]
