# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncmaster', '0006_auto_20180205_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='editedtablemap',
            name='old_targettable',
            field=models.CharField(default='user', max_length=100),
            preserve_default=False,
        ),
    ]
