# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('syncmaster', '0008_synccolumndetails_shortid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditedCOlumnMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('synccolumn_id', models.CharField(max_length=100)),
                ('synctable_id', models.CharField(max_length=100)),
                ('old_sourcefield', models.CharField(max_length=100)),
                ('old_targetfield', models.CharField(max_length=100)),
                ('pid', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
    ]
