# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180110_1527'),
        ('syncmaster', '0011_synccolumndetails_projectid'),
    ]

    operations = [
        migrations.AddField(
            model_name='editedcolumnmap',
            name='pid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='synccolumndetails',
            unique_together=set([('syncTable', 'sourcefield', 'targetfield', 'projectid')]),
        ),
    ]
