# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syncmaster', '0012_auto_20180206_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synccolumndetails',
            name='WHERECON',
        ),
    ]
