# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rolesetup', '0001_initial'),
        ('project', '0004_ionicnotification'),
        ('transactionview', '0016_auto_20180508_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('projectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationButtons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('button_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('stage_name', models.CharField(max_length=100)),
                ('status_process_type', models.CharField(blank=True, choices=[('Transaction', 'Transaction'), ('Report', 'Report'), ('Message', 'Message')], max_length=50, null=True)),
                ('status_process', models.CharField(blank=True, max_length=100, null=True)),
                ('action_event', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
                ('from_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_date_field', to='transactionview.Component')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.Notification')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rolesetup.Role')),
                ('to_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_date_field', to='transactionview.Component')),
            ],
        ),
        migrations.AddField(
            model_name='notificationbuttons',
            name='notification_configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.NotificationConfiguration'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationconfiguration',
            unique_together=set([('stage_name', 'notification')]),
        ),
        migrations.AlterUniqueTogether(
            name='notificationbuttons',
            unique_together=set([('notification_configuration', 'button_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set([('title', 'projectid')]),
        ),
    ]
