# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationconfiguration',
            name='choosed_status_process',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
