# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notificationconfiguration_pricelist_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationbuttons',
            name='notification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notification.Notification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationbuttons',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_stage', to='notification.NotificationConfiguration'),
        ),
        migrations.AlterField(
            model_name='notificationbuttons',
            name='notification_configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_stage', to='notification.NotificationConfiguration'),
        ),
        migrations.AlterField(
            model_name='notificationconfiguration',
            name='status_process_type',
            field=models.CharField(blank=True, choices=[('Transaction', 'Transaction'), ('Report', 'Report'), ('Buttons', 'Buttons'), ('Message', 'Message')], max_length=50, null=True),
        ),
    ]
