# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactionview', '0016_auto_20180508_1809'),
        ('notification', '0004_auto_20180611_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationconfiguration',
            name='user_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_user_field', to='transactionview.Component'),
        ),
    ]
