# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-01 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_auto_20180801_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationconfiguration',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
