# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transactionview', '0004_remove_component_sql_fire_db'),
        ('actions', '0003_auto_20180112_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('expression', models.TextField(blank=True, null=True)),
                ('expression_postfix', models.TextField(blank=True, null=True)),
                ('iconcls', models.CharField(blank=True, max_length=100, null=True)),
                ('actiontype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_action', to='actions.Actions')),
                ('transactionview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_trans', to='transactionview.Transactionview')),
                ('ui_control_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_ui', to='transactionview.Component')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
    ]
