# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_uploadaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadaction',
            name='actiontype',
        ),
        migrations.RemoveField(
            model_name='uploadaction',
            name='transactionview',
        ),
        migrations.RemoveField(
            model_name='uploadaction',
            name='ui_control_field',
        ),
        migrations.DeleteModel(
            name='UploadAction',
        ),
    ]
