# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transactionview', '0016_auto_20180508_1809'),
        ('actions', '0005_auto_20180308_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('expression', models.TextField(blank=True, null=True)),
                ('expression_postfix', models.TextField(blank=True, null=True)),
                ('iconcls', models.CharField(blank=True, choices=[('add', 'Add'), ('albums', 'Albums'), ('logo-android', 'Android'), ('logo-angular', 'Angular'), ('aperture', 'Aperture'), ('logo-apple', 'Apple'), ('apps', 'Apps'), ('archive', 'Archive'), ('barcode', 'Barcode'), ('basket', 'Basket'), ('bicycle', 'Bicycle'), ('logo-bitcoin', 'Bitcoin'), ('bonfire', 'Bonefire'), ('book', 'Book'), ('bookmark', 'Bookmark'), ('bookmarks', 'Bookmarks'), ('briefcase', 'Briefcase'), ('calculator', 'Calculator'), ('calendar', 'Calendar'), ('card', 'Card'), ('cash', 'Cash'), ('clock', 'Clock'), ('cloud', 'Cloud'), ('codepen', 'Codepen'), ('construct', 'Construct'), ('contact', 'Contact'), ('copy', 'Copy'), ('create', 'Create'), ('cube', 'Cube'), ('desktop', 'Desktop'), ('disc', 'Disc'), ('document', 'Document'), ('flame', 'Flame'), ('flower', 'Flower'), ('floder', 'Floder'), ('globe', 'Globe'), ('grid', 'Grid'), ('help-buoy', 'Help-Buoy'), ('home', 'Home'), ('images', 'Images'), ('information-circle', 'Information-Circle'), ('keypad', 'Keypad'), ('laptop', 'Laptop'), ('list-box', 'List-Box'), ('lock', 'Lock')], max_length=100, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.AlterField(
            model_name='actions',
            name='actiontype',
            field=models.CharField(blank=True, choices=[('cancel', 'Cancel'), ('delete', 'Delete'), ('new', 'New'), ('save', 'Save'), ('search', 'Search'), ('notify', 'notify')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cancelaction',
            name='iconcls',
            field=models.CharField(blank=True, choices=[('add', 'Add'), ('albums', 'Albums'), ('logo-android', 'Android'), ('logo-angular', 'Angular'), ('aperture', 'Aperture'), ('logo-apple', 'Apple'), ('apps', 'Apps'), ('archive', 'Archive'), ('barcode', 'Barcode'), ('basket', 'Basket'), ('bicycle', 'Bicycle'), ('logo-bitcoin', 'Bitcoin'), ('bonfire', 'Bonefire'), ('book', 'Book'), ('bookmark', 'Bookmark'), ('bookmarks', 'Bookmarks'), ('briefcase', 'Briefcase'), ('calculator', 'Calculator'), ('calendar', 'Calendar'), ('card', 'Card'), ('cash', 'Cash'), ('clock', 'Clock'), ('cloud', 'Cloud'), ('codepen', 'Codepen'), ('construct', 'Construct'), ('contact', 'Contact'), ('copy', 'Copy'), ('create', 'Create'), ('cube', 'Cube'), ('desktop', 'Desktop'), ('disc', 'Disc'), ('document', 'Document'), ('flame', 'Flame'), ('flower', 'Flower'), ('floder', 'Floder'), ('globe', 'Globe'), ('grid', 'Grid'), ('help-buoy', 'Help-Buoy'), ('home', 'Home'), ('images', 'Images'), ('information-circle', 'Information-Circle'), ('keypad', 'Keypad'), ('laptop', 'Laptop'), ('list-box', 'List-Box'), ('lock', 'Lock')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deleteaction',
            name='iconcls',
            field=models.CharField(blank=True, choices=[('add', 'Add'), ('albums', 'Albums'), ('logo-android', 'Android'), ('logo-angular', 'Angular'), ('aperture', 'Aperture'), ('logo-apple', 'Apple'), ('apps', 'Apps'), ('archive', 'Archive'), ('barcode', 'Barcode'), ('basket', 'Basket'), ('bicycle', 'Bicycle'), ('logo-bitcoin', 'Bitcoin'), ('bonfire', 'Bonefire'), ('book', 'Book'), ('bookmark', 'Bookmark'), ('bookmarks', 'Bookmarks'), ('briefcase', 'Briefcase'), ('calculator', 'Calculator'), ('calendar', 'Calendar'), ('card', 'Card'), ('cash', 'Cash'), ('clock', 'Clock'), ('cloud', 'Cloud'), ('codepen', 'Codepen'), ('construct', 'Construct'), ('contact', 'Contact'), ('copy', 'Copy'), ('create', 'Create'), ('cube', 'Cube'), ('desktop', 'Desktop'), ('disc', 'Disc'), ('document', 'Document'), ('flame', 'Flame'), ('flower', 'Flower'), ('floder', 'Floder'), ('globe', 'Globe'), ('grid', 'Grid'), ('help-buoy', 'Help-Buoy'), ('home', 'Home'), ('images', 'Images'), ('information-circle', 'Information-Circle'), ('keypad', 'Keypad'), ('laptop', 'Laptop'), ('list-box', 'List-Box'), ('lock', 'Lock')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newaction',
            name='iconcls',
            field=models.CharField(blank=True, choices=[('add', 'Add'), ('albums', 'Albums'), ('logo-android', 'Android'), ('logo-angular', 'Angular'), ('aperture', 'Aperture'), ('logo-apple', 'Apple'), ('apps', 'Apps'), ('archive', 'Archive'), ('barcode', 'Barcode'), ('basket', 'Basket'), ('bicycle', 'Bicycle'), ('logo-bitcoin', 'Bitcoin'), ('bonfire', 'Bonefire'), ('book', 'Book'), ('bookmark', 'Bookmark'), ('bookmarks', 'Bookmarks'), ('briefcase', 'Briefcase'), ('calculator', 'Calculator'), ('calendar', 'Calendar'), ('card', 'Card'), ('cash', 'Cash'), ('clock', 'Clock'), ('cloud', 'Cloud'), ('codepen', 'Codepen'), ('construct', 'Construct'), ('contact', 'Contact'), ('copy', 'Copy'), ('create', 'Create'), ('cube', 'Cube'), ('desktop', 'Desktop'), ('disc', 'Disc'), ('document', 'Document'), ('flame', 'Flame'), ('flower', 'Flower'), ('floder', 'Floder'), ('globe', 'Globe'), ('grid', 'Grid'), ('help-buoy', 'Help-Buoy'), ('home', 'Home'), ('images', 'Images'), ('information-circle', 'Information-Circle'), ('keypad', 'Keypad'), ('laptop', 'Laptop'), ('list-box', 'List-Box'), ('lock', 'Lock')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='saveaction',
            name='iconcls',
            field=models.CharField(blank=True, choices=[('add', 'Add'), ('albums', 'Albums'), ('logo-android', 'Android'), ('logo-angular', 'Angular'), ('aperture', 'Aperture'), ('logo-apple', 'Apple'), ('apps', 'Apps'), ('archive', 'Archive'), ('barcode', 'Barcode'), ('basket', 'Basket'), ('bicycle', 'Bicycle'), ('logo-bitcoin', 'Bitcoin'), ('bonfire', 'Bonefire'), ('book', 'Book'), ('bookmark', 'Bookmark'), ('bookmarks', 'Bookmarks'), ('briefcase', 'Briefcase'), ('calculator', 'Calculator'), ('calendar', 'Calendar'), ('card', 'Card'), ('cash', 'Cash'), ('clock', 'Clock'), ('cloud', 'Cloud'), ('codepen', 'Codepen'), ('construct', 'Construct'), ('contact', 'Contact'), ('copy', 'Copy'), ('create', 'Create'), ('cube', 'Cube'), ('desktop', 'Desktop'), ('disc', 'Disc'), ('document', 'Document'), ('flame', 'Flame'), ('flower', 'Flower'), ('floder', 'Floder'), ('globe', 'Globe'), ('grid', 'Grid'), ('help-buoy', 'Help-Buoy'), ('home', 'Home'), ('images', 'Images'), ('information-circle', 'Information-Circle'), ('keypad', 'Keypad'), ('laptop', 'Laptop'), ('list-box', 'List-Box'), ('lock', 'Lock')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='searchaction',
            name='iconcls',
            field=models.CharField(blank=True, choices=[('add', 'Add'), ('albums', 'Albums'), ('logo-android', 'Android'), ('logo-angular', 'Angular'), ('aperture', 'Aperture'), ('logo-apple', 'Apple'), ('apps', 'Apps'), ('archive', 'Archive'), ('barcode', 'Barcode'), ('basket', 'Basket'), ('bicycle', 'Bicycle'), ('logo-bitcoin', 'Bitcoin'), ('bonfire', 'Bonefire'), ('book', 'Book'), ('bookmark', 'Bookmark'), ('bookmarks', 'Bookmarks'), ('briefcase', 'Briefcase'), ('calculator', 'Calculator'), ('calendar', 'Calendar'), ('card', 'Card'), ('cash', 'Cash'), ('clock', 'Clock'), ('cloud', 'Cloud'), ('codepen', 'Codepen'), ('construct', 'Construct'), ('contact', 'Contact'), ('copy', 'Copy'), ('create', 'Create'), ('cube', 'Cube'), ('desktop', 'Desktop'), ('disc', 'Disc'), ('document', 'Document'), ('flame', 'Flame'), ('flower', 'Flower'), ('floder', 'Floder'), ('globe', 'Globe'), ('grid', 'Grid'), ('help-buoy', 'Help-Buoy'), ('home', 'Home'), ('images', 'Images'), ('information-circle', 'Information-Circle'), ('keypad', 'Keypad'), ('laptop', 'Laptop'), ('list-box', 'List-Box'), ('lock', 'Lock')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notifyaction',
            name='actiontype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notify_action', to='actions.Actions'),
        ),
        migrations.AddField(
            model_name='notifyaction',
            name='transactionview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notify_trans', to='transactionview.Transactionview'),
        ),
        migrations.AddField(
            model_name='notifyaction',
            name='ui_control_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Notify_ui', to='transactionview.Component'),
        ),
    ]
