# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_auto_20180508_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifyaction',
            name='ui_control_field',
        ),
        migrations.AlterField(
            model_name='actions',
            name='actiontype',
            field=models.CharField(blank=True, choices=[('cancel', 'Cancel'), ('delete', 'Delete'), ('new', 'New'), ('save', 'Save'), ('search', 'Search'), ('notify', 'Notify')], max_length=50, null=True),
        ),
    ]
