# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactionview', '0016_auto_20180508_1809'),
        ('actions', '0007_auto_20180509_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifyaction',
            name='product_list_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_ui', to='transactionview.Component'),
        ),
        migrations.AddField(
            model_name='notifyaction',
            name='text_message_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msg_ui', to='transactionview.Component'),
        ),
        migrations.AddField(
            model_name='notifyaction',
            name='to_user_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user_ui', to='transactionview.Component'),
        ),
    ]
