# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0018_auto_20180327_1115'),
        ('actions', '0010_remove_notifyaction_product_parent_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifyaction',
            name='product_list_field',
        ),
        migrations.AddField(
            model_name='notifyaction',
            name='notification_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_table', to='transaction.Txtabledetails'),
        ),
        migrations.AlterField(
            model_name='notifyaction',
            name='text_message_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msg_ui', to='transactionview.Component'),
        ),
        migrations.AlterField(
            model_name='notifyaction',
            name='user_list_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_user_ui', to='transactionview.Component'),
        ),
    ]
