# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0011_auto_20180515_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifyaction',
            name='actiontype',
        ),
        migrations.RemoveField(
            model_name='notifyaction',
            name='notification_table',
        ),
        migrations.RemoveField(
            model_name='notifyaction',
            name='text_message_field',
        ),
        migrations.RemoveField(
            model_name='notifyaction',
            name='transactionview',
        ),
        migrations.RemoveField(
            model_name='notifyaction',
            name='user_list_field',
        ),
        migrations.DeleteModel(
            name='NotifyAction',
        ),
    ]
