# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transactionview', '0016_auto_20180508_1809'),
        ('actions', '0013_auto_20180531_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='TxnPrintFormatAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('iconcls', models.CharField(blank=True, max_length=50, null=True)),
                ('expression', models.TextField(blank=True, null=True)),
                ('JasperFile', models.FileField(upload_to='static/ionicmeta')),
                ('parameter', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.AlterField(
            model_name='actions',
            name='actiontype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='actions',
            name='transactionviewid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_type', to='transactionview.Transactionview'),
        ),
        migrations.AlterField(
            model_name='cancelaction',
            name='iconcls',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deleteaction',
            name='iconcls',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newaction',
            name='iconcls',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='saveaction',
            name='iconcls',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='searchaction',
            name='iconcls',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='txnprintformataction',
            name='actiontype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txnprintfomat_action', to='actions.Actions'),
        ),
        migrations.AddField(
            model_name='txnprintformataction',
            name='transactionview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txnprintfomat_trans', to='transactionview.Transactionview'),
        ),
        migrations.AddField(
            model_name='txnprintformataction',
            name='ui_control_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='txnprintfomat_ui', to='transactionview.Component'),
        ),
    ]
