# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-18 05:59
from __future__ import unicode_literals

import actions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0015_auto_20180718_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txnprintformataction',
            name='JasperFile',
            field=models.FileField(upload_to=actions.models.user_directory_path),
        ),
    ]
