# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-06 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printformat', '0002_remove_printformat_iconcls'),
        ('actions', '0016_auto_20180718_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='txnprintformataction',
            name='JasperFile',
        ),
        migrations.RemoveField(
            model_name='txnprintformataction',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='txnprintformataction',
            name='title',
        ),
        migrations.AddField(
            model_name='txnprintformataction',
            name='pfConfig',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='printformat.PrintFormat'),
            preserve_default=False,
        ),
    ]
