# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-06 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0017_auto_20180806_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='txnprintformataction',
            old_name='pfConfig',
            new_name='pfconfig',
        ),
    ]
