# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-21 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0018_auto_20180806_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchaction',
            name='param_fields',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='searchaction',
            name='search_field',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
