# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-03 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transactionview', '0023_auto_20180824_1149'),
        ('actions', '0019_auto_20180821_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSyncAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('iconcls', models.CharField(blank=True, max_length=50, null=True)),
                ('expression', models.TextField(blank=True, null=True)),
                ('actiontype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='googlesync_action', to='actions.Actions')),
                ('transactionview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='googlesync_trans', to='transactionview.Transactionview')),
                ('ui_control_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='googlesync_ui', to='transactionview.Component')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
    ]
