# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-03 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0020_googlesyncaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlesyncaction',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
