# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='enumkeyvalue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='enumtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='statusoftable',
            name='columnId',
        ),
        migrations.RemoveField(
            model_name='statusoftable',
            name='projectId',
        ),
        migrations.RemoveField(
            model_name='statusoftable',
            name='tableId',
        ),
        migrations.RemoveField(
            model_name='statusoftable',
            name='transactionId',
        ),
        migrations.DeleteModel(
            name='statusOfTable',
        ),
    ]
