# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20180103_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='txtabledetails',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default='0', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='txtabledetails',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default='0', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='txtabledetails',
            name='parent_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.Txtabledetails'),
        ),
        migrations.AddField(
            model_name='txtabledetails',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, default='0', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='txtabledetails',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default='0', editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='txtablecomponentdetails',
            name='no_of_decimal_digits',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
