# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20180103_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='txtabledetails',
            old_name='parent_table',
            new_name='parent',
        ),
    ]
