# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_auto_20180103_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='txtablecomponentdetails',
            name='is_system_component',
            field=models.BooleanField(default=False),
        ),
    ]
