# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_auto_20180105_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='enumkeyvalue',
            name='enum_title_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transaction.enumtitle'),
            preserve_default=False,
        ),
    ]
