# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_enumkeyvalue_enum_title_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='txtablecomponentdetails',
            name='enum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.enumtitle'),
        ),
    ]
