# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0018_auto_20180327_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='txtablecomponentdetails',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('modified', 'modified'), ('deleted', 'deleted')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='txtabledetails',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('modified', 'modified'), ('deleted', 'deleted')], max_length=20, null=True),
        ),
    ]
