# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_emailconfiguration_db_status'),
        ('transaction', '0020_auto_20180628_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txtablecomponentdetails',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('modified', 'modified'), ('updated', 'updated'), ('deleted', 'deleted')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='txtabledetails',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('modified', 'modified'), ('updated', 'updated'), ('deleted', 'deleted')], max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='txtabledetails',
            unique_together=set([('table_slug', 'projectid')]),
        ),
    ]
