# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0021_auto_20180628_1547'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='txtablecomponentdetails',
            unique_together=set([('field_slug', 'txtabledetailid')]),
        ),
    ]
