# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0022_auto_20180628_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txtablecomponentdetails',
            name='datatype',
            field=models.CharField(choices=[('AutoField', 'AutoField'), ('BinaryField', 'BinaryField'), ('BooleanField', 'BooleanField'), ('DateField', 'DateField'), ('DateTimeField', 'DateTimeField'), ('DecimalField', 'DecimalField'), ('EmailField', 'EmailField'), ('FileField', 'FileField'), ('ImageField', 'ImageField'), ('IntegerField', 'IntegerField'), ('TextField', 'TextField'), ('CharField', 'CharField'), ('UUIDField', 'UUIDField'), ('ForeignKey_int', 'ForeignKey_int'), ('ForeignKey_char', 'ForeignKey_char'), ('ForeignKey_date', 'ForeignKey_date'), ('Enum_Int', 'Enum_Int'), ('Enum_Char', 'Enum_Char'), ('Enum_Date', 'Enum_Date'), ('ButtonField', 'ButtonField'), ('MacroField', 'MacroField'), ('OneToOneField', 'OneToOneField')], max_length=50),
        ),
        migrations.AlterField(
            model_name='txtablecomponentdetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile'),
        ),
        migrations.AlterField(
            model_name='txtabledetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile'),
        ),
    ]
