# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=b'title', verbose_name='slug')),
            ],
            options={
                'db_table': 'report_componenttype',
                'verbose_name': 'ComponentType',
                'verbose_name_plural': 'ComponentTypes',
            },
        ),
        migrations.CreateModel(
            name='WidgetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=b'title', verbose_name='slug')),
            ],
            options={
                'db_table': 'report_widgettype',
                'verbose_name': 'WidgetType',
                'verbose_name_plural': 'WidgetTypes',
            },
        ),
    ]
