# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0004_ionicnotification'),
        ('reportview', '0001_initial'),
        ('transactionview', '0016_auto_20180508_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('menutype', models.CharField(blank=True, choices=[('grid', 'Grid'), ('sidemenu', 'SideMenu')], max_length=50, null=True)),
                ('column', models.CharField(blank=True, choices=[('one', 'One'), ('two', 'Two'), ('three', 'Three')], max_length=50, null=True)),
                ('sidemenu', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right'), ('bottom', 'Bottom')], max_length=50, null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom2_url_params', to='project.Project')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('iconcls', models.CharField(choices=[('add', 'Add'), ('albums', 'Albums'), ('logo-android', 'Android'), ('logo-angular', 'Angular'), ('aperture', 'Aperture'), ('logo-apple', 'Apple'), ('apps', 'Apps'), ('archive', 'Archive'), ('barcode', 'Barcode'), ('basket', 'Basket'), ('bicycle', 'Bicycle'), ('logo-bitcoin', 'Bitcoin'), ('bonfire', 'Bonefire'), ('book', 'Book'), ('bookmark', 'Bookmark'), ('bookmarks', 'Bookmarks'), ('briefcase', 'Briefcase'), ('calculator', 'Calculator'), ('calendar', 'Calendar'), ('card', 'Card'), ('cash', 'Cash'), ('clock', 'Clock'), ('cloud', 'Cloud'), ('codepen', 'Codepen'), ('construct', 'Construct'), ('contact', 'Contact'), ('copy', 'Copy'), ('create', 'Create'), ('cube', 'Cube'), ('desktop', 'Desktop'), ('disc', 'Disc'), ('document', 'Document'), ('flame', 'Flame'), ('flower', 'Flower'), ('floder', 'Floder'), ('globe', 'Globe'), ('grid', 'Grid'), ('help-buoy', 'Help-Buoy'), ('home', 'Home'), ('images', 'Images'), ('information-circle', 'Information-Circle'), ('keypad', 'Keypad'), ('laptop', 'Laptop'), ('list-box', 'List-Box'), ('lock', 'Lock')], max_length=100)),
                ('typeofview', models.CharField(blank=True, choices=[('transactionview', 'Transactionview'), ('reportview', 'Reportview')], max_length=100, null=True)),
                ('createpage', models.BooleanField(default=False)),
                ('homepageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom3_url_params', to='hometemplate.Homepage')),
                ('reportview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom5_url_params', to='reportview.Report')),
                ('transactionview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom4_url_params', to='transactionview.Transactionview')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
    ]
