# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-05 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_googleapisetup'),
        ('hometemplate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('pageoption', models.CharField(choices=[('default', 'Default'), ('other', 'Other')], max_length=50)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.AlterField(
            model_name='menu',
            name='iconcls',
            field=models.CharField(choices=[('add', 'Add'), ('albums', 'Albums'), ('logo-android', 'Android'), ('logo-angular', 'Angular'), ('aperture', 'Aperture'), ('logo-apple', 'Apple'), ('apps', 'Apps'), ('archive', 'Archive'), ('barcode', 'Barcode'), ('basket', 'Basket'), ('bicycle', 'Bicycle'), ('logo-bitcoin', 'Bitcoin'), ('bonfire', 'Bonefire'), ('book', 'Book'), ('bookmark', 'Bookmark'), ('bookmarks', 'Bookmarks'), ('briefcase', 'Briefcase'), ('calculator', 'Calculator'), ('calendar', 'Calendar'), ('card', 'Card'), ('cash', 'Cash'), ('clock', 'Clock'), ('cloud', 'Cloud'), ('logo-codepen', 'Codepen'), ('construct', 'Construct'), ('contact', 'Contact'), ('copy', 'Copy'), ('create', 'Create'), ('cube', 'Cube'), ('desktop', 'Desktop'), ('disc', 'Disc'), ('document', 'Document'), ('flame', 'Flame'), ('flower', 'Flower'), ('floder', 'Floder'), ('globe', 'Globe'), ('grid', 'Grid'), ('help-buoy', 'Help-Buoy'), ('home', 'Home'), ('images', 'Images'), ('information-circle', 'Information-Circle'), ('keypad', 'Keypad'), ('laptop', 'Laptop'), ('list-box', 'List-Box'), ('lock', 'Lock'), ('locate', 'Locate'), ('logo-pinterest', 'Pinterest'), ('nuclear', 'Nuclear'), ('pie', 'Pie'), ('stats', 'Stats'), ('stopwatch', 'Stopwatch'), ('tennisball', 'Tennisball'), ('thumbs-up', 'Thumbs-up')], max_length=100),
        ),
        migrations.AddField(
            model_name='rootpage',
            name='pageValue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pgvale_url_params', to='hometemplate.Menu'),
        ),
        migrations.AddField(
            model_name='rootpage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgvalue2_url_params', to='project.Project'),
        ),
    ]
