# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaction', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('is_readonly', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=False)),
                ('allow_duplicate', models.BooleanField(default=False)),
                ('widgettype', models.CharField(blank=True, choices=[('button', 'Button'), ('check', 'Checkbox'), ('date', 'Date'), ('email', 'Email'), ('password', 'Password'), ('number', 'Number'), ('select', 'Select'), ('text', 'Text'), ('time', 'Time'), ('textarea', 'Textarea'), ('radio', 'Radiobox'), ('list', 'List')], max_length=50, null=True)),
                ('expression', models.CharField(blank=True, max_length=100, null=True)),
                ('validateexp', models.CharField(blank=True, max_length=100, null=True)),
                ('sql', models.CharField(blank=True, max_length=1000, null=True)),
                ('displayorder', models.BigIntegerField(blank=True, null=True)),
                ('identifiers', models.CharField(blank=True, max_length=150, null=True)),
                ('componentrefer_id', models.BigIntegerField(blank=True, null=True)),
                ('componenttype', models.CharField(blank=True, max_length=150, null=True)),
                ('dbcolumn', models.CharField(blank=True, max_length=150, null=True)),
                ('componentrefer_dt', models.CharField(blank=True, max_length=15000, null=True)),
                ('modeOfEntry', models.CharField(blank=True, choices=[('tbe', 'ToBeEnter'), ('tbc', 'ToBeCalculate')], max_length=50, null=True)),
                ('suggestive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=100)),
                ('containertype', models.CharField(blank=True, choices=[('card', 'Card'), ('list', 'List'), ('grid', 'Grid')], max_length=50, null=True)),
                ('inputtype', models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('floating', 'Floating'), ('inline', 'Inline'), ('inset', 'Inset'), ('placeholder', 'Placeholder'), ('stacked', 'Stacked')], max_length=50, null=True)),
                ('expression', models.CharField(blank=True, max_length=1000, null=True)),
                ('postexp', models.CharField(blank=True, max_length=1000, null=True)),
                ('displayorder', models.BigIntegerField(blank=True, null=True)),
                ('identifiers', models.CharField(blank=True, max_length=150, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='transactionview.Container')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transactionview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('viewtype', models.CharField(blank=True, choices=[('carousel', 'Carousel'), ('ng', 'None_Grid'), ('grid', 'Grid'), ('ng-grid', 'None_Grid Grid')], max_length=50, null=True)),
                ('projectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom1_url_params', to='project.Project')),
                ('transactionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom1_url_params', to='transaction.Transaction')),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='transactionviewid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom2_url_params', to='transactionview.Transactionview'),
        ),
        migrations.AddField(
            model_name='component',
            name='containerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom3_url_params', to='transactionview.Container'),
        ),
        migrations.AddField(
            model_name='component',
            name='transactionviewid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom3_url_params', to='transactionview.Transactionview'),
        ),
    ]
