# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionview', '0002_auto_20180111_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='sql_fire_db',
            field=models.CharField(blank=True, choices=[('tbe', 'ToBeEnter'), ('tbc', 'ToBeCalculate')], max_length=50, null=True),
        ),
    ]
