# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 04:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactionview', '0003_component_sql_fire_db'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='sql_fire_db',
        ),
    ]
