# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180224_1547'),
        ('transactionview', '0005_auto_20180316_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eupdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=100)),
                ('updatetype', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('both', 'Both')], max_length=50)),
                ('actiontype', models.CharField(choices=[('add', 'Add'), ('sub', 'Sub'), ('inc', 'Inc'), ('dec', 'Dec'), ('replace', 'Replace')], max_length=50)),
                ('filter_clause', models.CharField(max_length=1000)),
                ('projectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eupdate_projectid', to='project.Project')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.AlterField(
            model_name='component',
            name='widgettype',
            field=models.CharField(blank=True, choices=[('button', 'Button'), ('check', 'Checkbox'), ('date', 'Date'), ('email', 'Email'), ('password', 'Password'), ('number', 'Number'), ('select', 'Select'), ('text', 'Text'), ('time', 'Time'), ('textarea', 'Textarea'), ('radio', 'Radiobox'), ('scan', 'Scan'), ('upload', 'Upload'), ('stot', 'Speech-To-Text')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transactionview',
            name='savetype',
            field=models.CharField(blank=True, choices=[('offline', 'Offline'), ('online', 'Online'), ('both', 'Both')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eupdate',
            name='source_ui_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_ui', to='transactionview.Component'),
        ),
        migrations.AddField(
            model_name='eupdate',
            name='target_ui_filed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_ui', to='transactionview.Component'),
        ),
        migrations.AddField(
            model_name='eupdate',
            name='targettxview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eupdate_params', to='transactionview.Transactionview'),
        ),
        migrations.AddField(
            model_name='eupdate',
            name='transactionview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eupdate_txview_params', to='transactionview.Transactionview'),
        ),
        migrations.AddField(
            model_name='eupdate',
            name='ui_control_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_control', to='transactionview.Component'),
        ),
    ]
