# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactionview', '0006_auto_20180327_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eupdate',
            old_name='actiontype',
            new_name='action_type',
        ),
        migrations.AlterField(
            model_name='eupdate',
            name='ui_control_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ui_control', to='transactionview.Component'),
        ),
    ]
