# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180224_1547'),
        ('transactionview', '0007_auto_20180409_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('based_on_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactionview.Container')),
                ('projectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
                ('targettxview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epost_target_txview', to='transactionview.Transactionview')),
                ('transactionview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epost_src_txview', to='transactionview.Transactionview')),
                ('ui_control_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactionview.Component')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
    ]
