# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionview', '0008_epost'),
    ]

    operations = [
        migrations.AddField(
            model_name='epost',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
