# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactionview', '0011_auto_20180419_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epost',
            name='based_on_container',
        ),
        migrations.RemoveField(
            model_name='epost',
            name='projectid',
        ),
        migrations.RemoveField(
            model_name='epost',
            name='source_tx_view',
        ),
        migrations.RemoveField(
            model_name='epost',
            name='target_tx_view',
        ),
        migrations.RemoveField(
            model_name='epost',
            name='ui_control_field',
        ),
        migrations.RemoveField(
            model_name='epostmapfield',
            name='control_field',
        ),
        migrations.RemoveField(
            model_name='epostmapfield',
            name='epost',
        ),
        migrations.RemoveField(
            model_name='epostmapfield',
            name='group_field',
        ),
        migrations.RemoveField(
            model_name='epostmapfield',
            name='source_ui_field',
        ),
        migrations.RemoveField(
            model_name='epostmapfield',
            name='target_ui_filed',
        ),
        migrations.DeleteModel(
            name='Epost',
        ),
        migrations.DeleteModel(
            name='EpostMapField',
        ),
    ]
