# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionview', '0013_auto_20180426_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='epostmapfield',
            name='target_row',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='epostmapfield',
            name='order_by',
            field=models.BigIntegerField(default=0),
        ),
    ]
