# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-14 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transactionview', '0016_auto_20180508_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireSql',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('sql', models.CharField(max_length=1000)),
                ('transactionview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firesql_txview', to='transactionview.Transactionview')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='firesql',
            unique_together=set([('transactionview', 'slug')]),
        ),
    ]
