# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-24 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionview', '0017_auto_20180814_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionview',
            name='expression',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
