# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-24 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionview', '0021_remove_container_postfixexp'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionview',
            name='postfixexp',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
