# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-24 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionview', '0022_transactionview_postfixexp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionview',
            name='expression',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='transactionview',
            name='postfixexp',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
