# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-21 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionview', '0024_auto_20180905_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='txncssutilites',
            name='header_label_color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('dark', 'Dark')], default='dark', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='txncssutilites',
            name='label_color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('dark', 'Dark')], default='dark', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='inputtype',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('floating', 'Floating'), ('placeholder', 'Placeholder'), ('stacked', 'Stacked'), ('boxed', 'Boxed')], max_length=50, null=True),
        ),
    ]
