# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-01 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionview', '0025_auto_20180921_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='widgettype',
            field=models.CharField(blank=True, choices=[('button', 'Button'), ('check', 'Checkbox'), ('date', 'Date'), ('email', 'Email'), ('password', 'Password'), ('number', 'Number'), ('select', 'Select'), ('text', 'Text'), ('time', 'Time'), ('textarea', 'Textarea'), ('radio', 'Radiobox'), ('scan', 'Scan'), ('upload', 'Upload'), ('stot', 'Speech-To-Text'), ('dpop', 'Dynamic Popup')], max_length=50, null=True),
        ),
    ]
