# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemageneration', '0002_remove_generateschematablecomponent_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateschematablecomponent',
            name='primary',
            field=models.CharField(default='aish', max_length=100),
            preserve_default=False,
        ),
    ]
