# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemageneration', '0003_generateschematablecomponent_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generateschematablecomponent',
            name='primary',
        ),
    ]
