# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemageneration', '0004_remove_generateschematablecomponent_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateschemacomponent',
            name='ddl_type',
            field=models.CharField(choices=[('add', 'add'), ('modify', 'modify'), ('delete', 'delete')], default='add', max_length=10),
            preserve_default=False,
        ),
    ]
