# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemageneration', '0005_generateschemacomponent_ddl_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateschemacomponent',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.Txtablecomponentdetails'),
        ),
    ]
