# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemageneration', '0006_auto_20171230_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateschemacomponent',
            name='no_of_decimal_digits',
            field=models.BigIntegerField(null=True),
        ),
    ]
