# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemageneration', '0008_auto_20180104_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateschematablecomponent',
            name='isprimary',
            field=models.BooleanField(default=False),
        ),
    ]
