# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemageneration', '0009_generateschematablecomponent_isprimary'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateschemacomponent',
            name='db_type',
            field=models.CharField(default='server', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generateschematablecomponent',
            name='db_type',
            field=models.CharField(default='server', max_length=100),
            preserve_default=False,
        ),
    ]
