# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemageneration', '0011_auto_20180628_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateschemacomponent',
            name='db_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generateschemacomponent',
            name='ddl_type',
            field=models.CharField(blank=True, choices=[('add', 'add'), ('modify', 'modify'), ('delete', 'delete')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='generateschemacomponent',
            name='gen_schema_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schemageneration.GenerateSchemaTableComponent'),
        ),
    ]
