# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('schema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('ptype', models.CharField(choices=[('ecommerce', 'E-Commerce'), ('business', 'Business')], max_length=50)),
                ('application_type', models.CharField(choices=[('android', 'Android'), ('iOS', 'iOS'), ('windows', 'Windows')], max_length=50)),
                ('parentproject', models.CharField(max_length=200)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Projectwiseusersetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setasdefaultproject', models.BooleanField(default=False)),
                ('db_profileid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.Db_profile')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
        ),
    ]
