# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_ionicnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
