# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('server', models.CharField(blank=True, max_length=50, null=True)),
                ('port', models.BigIntegerField(blank=True, null=True)),
                ('email_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pwd', models.CharField(blank=True, max_length=50, null=True)),
                ('Domain', models.CharField(blank=True, max_length=50, null=True)),
                ('default_email_id', models.CharField(blank=True, max_length=200, null=True)),
                ('protocol', models.CharField(blank=True, max_length=200, null=True)),
                ('is_aunthentication_req', models.BooleanField(default=False)),
                ('support_tls', models.BooleanField(default=False)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
    ]
