# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_emailconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfiguration',
            name='db_status',
            field=models.CharField(choices=[('new', 'new'), ('edited', 'edited'), ('updated', 'updated'), ('deleted', 'deleted')], default='new', max_length=250),
            preserve_default=False,
        ),
    ]
