# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-21 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_remove_ionicservices_basicid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ionicservices',
            name='basicid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='dark',
            field=models.CharField(blank=True, default='#000000', max_length=100, null=True),
        ),
    ]
