# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-04 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20180921_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='imei_based_login',
            field=models.BooleanField(default=False),
        ),
    ]
