# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Db_connections_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('dbname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=100)),
                ('vendor', models.CharField(choices=[('mysql', 'Mysql'), ('oracle', 'Oracle'), ('sqllite', 'Sqllite'), ('mongodb', 'Mongodb')], max_length=100)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Db_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('admindb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schema.Db_connections_info')),
                ('appdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schema.Db_connections_info')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
        ),
    ]
