# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_connections_info',
            name='vendor',
            field=models.CharField(choices=[('mysql', 'Mysql'), ('oracle', 'Oracle'), ('sqlite', 'Sqlite'), ('mongodb', 'Mongodb')], max_length=100),
        ),
    ]
