# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0004_auto_20180119_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_profile',
            name='clientdb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schema.Db_connections_info'),
        ),
    ]
