# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0005_db_profile_clientdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_connections_info',
            name='sid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
