# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0006_db_connections_info_sid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_profile',
            name='admindb',
        ),
    ]
