# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-03 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0009_googleapisetup'),
        ('transactionview', '0023_auto_20180824_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='TxnMappingForEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', models.CharField(max_length=150)),
                ('email_reminder', models.CharField(blank=True, max_length=20, null=True)),
                ('popup_reminder', models.CharField(blank=True, max_length=20, null=True)),
                ('event_desc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_desc', to='transactionview.Component')),
                ('event_end_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_end_day', to='transactionview.Component')),
                ('event_end_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_end_time', to='transactionview.Component')),
                ('event_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_location', to='transactionview.Component')),
                ('event_start_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_start_day', to='transactionview.Component')),
                ('event_start_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_start_time', to='transactionview.Component')),
                ('event_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_title', to='transactionview.Component')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
                ('txview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactionview.Transactionview')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
