# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-03 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventconfiguration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txnmappingforevent',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
