# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-04 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventconfiguration', '0003_auto_20180903_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txnmappingforevent',
            name='event_start_time',
            field=models.ForeignKey(default=41, on_delete=django.db.models.deletion.CASCADE, related_name='event_start_time', to='transactionview.Component'),
            preserve_default=False,
        ),
    ]
