# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smssetup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsserver',
            name='server',
            field=models.CharField(max_length=200),
        ),
    ]
