# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smssetup', '0003_auto_20180504_1610'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='smsattributes',
            unique_together=set([('key', 'smsserver')]),
        ),
    ]
