# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smssetup', '0004_auto_20180504_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsattributes',
            name='db_status',
            field=models.CharField(choices=[('new', 'new'), ('edited', 'edited'), ('updated', 'updated'), ('deleted', 'deleted')], default='new', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smsserver',
            name='db_status',
            field=models.CharField(choices=[('new', 'new'), ('edited', 'edited'), ('updated', 'updated'), ('deleted', 'deleted')], default='new', max_length=250),
            preserve_default=False,
        ),
    ]
