# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smssetup', '0006_editedsmsattributes_editedsmsserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='editedsmsattributes',
            name='smsattr_id',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
