# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smssetup', '0007_editedsmsattributes_smsattr_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditedSMSServer',
        ),
    ]
