# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smssetup', '0008_delete_editedsmsserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsserver',
            name='use_proxy',
            field=models.BooleanField(default=False),
        ),
    ]
