# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smssetup', '0013_smsattributes_do'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsattributes',
            name='do',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
