# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportview', '0002_reportsubmit_click_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='slug',
        ),
    ]
