# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-18 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportview', '0005_newaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportprintformataction',
            name='project',
        ),
        migrations.RemoveField(
            model_name='reportprintformataction',
            name='report',
        ),
    ]
