# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-18 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import reportview.models


class Migration(migrations.Migration):

    dependencies = [
        ('reportview', '0006_auto_20180718_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportprintformataction',
            name='JasperFile',
            field=models.FileField(default=1, upload_to=reportview.models.user_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportprintformataction',
            name='parameter',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
