# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-25 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportview', '0009_auto_20180725_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfield',
            name='expression',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportfield',
            name='validate_expression',
            field=models.TextField(blank=True, null=True),
        ),
    ]
