# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportview', '0012_auto_20180727_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportprintformataction',
            name='report_params',
        ),
        migrations.RemoveField(
            model_name='reportprintformataction',
            name='report_type',
        ),
    ]
