# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportview', '0015_auto_20180728_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportprintformataction',
            name='click_event',
        ),
    ]
