# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportview', '0016_remove_reportprintformataction_click_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printformatactionsql',
            name='sql_type',
            field=models.CharField(choices=[(b'Grid', b'Grid'), (b'Nongrid', b'Nongrid')], max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='printformatactionsql',
            unique_together=set([('printformataction', 'do')]),
        ),
    ]
