# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportview', '0017_auto_20180728_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printformatactionsql',
            name='sql_type',
            field=models.CharField(choices=[(b'Nongrid', b'Nongrid'), (b'Grid', b'Grid')], max_length=100),
        ),
    ]
