# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-02 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportview', '0018_auto_20180728_1614'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='printformatactionsql',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='printformatactionsql',
            name='printformataction',
        ),
        migrations.DeleteModel(
            name='PrintFormatActionSQL',
        ),
    ]
