# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-02 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportview', '0019_auto_20180802_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportprintformataction',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='reportprintformataction',
            name='htmlfile',
        ),
        migrations.RemoveField(
            model_name='reportprintformataction',
            name='iconcls',
        ),
    ]
