# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-02 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printformat', '0001_initial'),
        ('reportview', '0020_auto_20180802_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportprintformataction',
            name='pfconfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='printformat.PrintFormat'),
        ),
    ]
