# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-02 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportview', '0021_reportprintformataction_pfconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportprintformataction',
            name='click_event',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
