# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-24 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportview', '0024_auto_20180824_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfield',
            name='data_type',
            field=models.CharField(blank=True, choices=[(b'char', b'Char'), (b'numeric', b'Numeric'), (b'datetime', b'DateTime'), (b'template_column', b'Template Column'), (b'button', b'Button')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reportparamfield',
            name='data_type',
            field=models.CharField(blank=True, choices=[(b'char', b'Char'), (b'numeric', b'Numeric'), (b'datetime', b'DateTime'), (b'template_column', b'Template Column'), (b'button', b'Button')], max_length=20, null=True),
        ),
    ]
