# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-27 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportview', '0025_auto_20180824_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='graphtype',
            field=models.CharField(blank=True, choices=[(b'column', b'Column chart'), (b'line', b'Line chart'), (b'pie', b'Pie chart'), (b'bar', b'Bar chart')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='showxyaxis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='xcoordinates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reportview.ReportField'),
        ),
        migrations.AddField(
            model_name='report',
            name='ycoordinates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reportview.ReportField'),
        ),
    ]
