# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-27 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportview', '0026_auto_20180827_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(blank=True, choices=[(b'onlinereport', b'OnlineReport'), (b'offlinereport', b'OfflineReport'), (b'displayreport', b'Displayreport'), (b'graphicalreport', b'Graphicalreport')], max_length=20, null=True),
        ),
    ]
