# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-11 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportview', '0027_auto_20180827_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportparamfield',
            name='sql',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
