# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-01 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import printformat.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0007_emailconfiguration_db_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('iconcls', models.CharField(blank=True, choices=[('add', 'Add'), ('albums', 'Albums'), ('logo-android', 'Android'), ('logo-angular', 'Angular'), ('aperture', 'Aperture'), ('logo-apple', 'Apple'), ('apps', 'Apps'), ('archive', 'Archive'), ('barcode', 'Barcode'), ('basket', 'Basket'), ('bicycle', 'Bicycle'), ('logo-bitcoin', 'Bitcoin'), ('bonfire', 'Bonefire'), ('book', 'Book'), ('bookmark', 'Bookmark'), ('bookmarks', 'Bookmarks'), ('briefcase', 'Briefcase'), ('calculator', 'Calculator'), ('calendar', 'Calendar'), ('card', 'Card'), ('cash', 'Cash'), ('clock', 'Clock'), ('cloud', 'Cloud'), ('codepen', 'Codepen'), ('construct', 'Construct'), ('contact', 'Contact'), ('copy', 'Copy'), ('create', 'Create'), ('cube', 'Cube'), ('desktop', 'Desktop'), ('disc', 'Disc'), ('document', 'Document'), ('flame', 'Flame'), ('flower', 'Flower'), ('floder', 'Floder'), ('globe', 'Globe'), ('grid', 'Grid'), ('help-buoy', 'Help-Buoy'), ('home', 'Home'), ('images', 'Images'), ('information-circle', 'Information-Circle'), ('keypad', 'Keypad'), ('laptop', 'Laptop'), ('list-box', 'List-Box'), ('lock', 'Lock')], max_length=100, null=True)),
                ('action_type', models.CharField(choices=[('Server', 'Server'), ('Client', 'Client')], max_length=100)),
                ('htmlfile', models.FileField(upload_to=printformat.models.user_directory_path)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrintFormatSQL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql', models.CharField(blank=True, max_length=500, null=True)),
                ('do', models.PositiveSmallIntegerField(default=0)),
                ('sql_type', models.CharField(choices=[('Nongrid', 'Nongrid'), ('Grid', 'Grid')], max_length=100)),
                ('printformat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printformat.PrintFormat')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='printformatsql',
            unique_together=set([('printformat', 'do')]),
        ),
    ]
