# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-05 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_googleapisetup'),
        ('printformat', '0003_printformat_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='printformat',
            unique_together=set([('project', 'slug')]),
        ),
    ]
