# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-05 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import printformat.models


class Migration(migrations.Migration):

    dependencies = [
        ('printformat', '0005_printformat_cssfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printformat',
            name='cssfile',
            field=models.FileField(blank=True, null=True, upload_to=printformat.models.user_directory_path),
        ),
    ]
