# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-05 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printformat', '0006_auto_20180905_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printformat',
            name='cssfile',
        ),
    ]
